### ISSUE TITLE
Update to Matomo 5.x and Marketplace

### ISSUE THREAD

**Issue by mikkeschiren** [digitalist-se/plugin-SentryLogger#6]
Hi,

We (Digitalist) have done some major updates on this plugin that we want to contribute back, but we also want the plugin to be visibble on Matomo Marketplace and continue to contribute. So we have a couple of questions:

* Are you interested in continue the work on the Sentry plugin, or could we (Digitalist) take it over?
* Could a GPL license be added?

**Comment by Findus23** [comment]
Hi,

Thanks for the message. That plugin was anyway never something I wanted to maintain, but more of a quick experiment (especially to collect deprecation warnings on upcoming php versions). So feel free to take over the plugin (I can even give you ownership to the repository if you want to migrate it to your github account) and contact the Matomo team to fix things in the marketplace afterwards.

I also now explicitly added the license in https://github.com/Findus23/plugin-SentryLogger/commit/721562ef0780f204596026cfeeb83ac5f6b7d9cd

**Comment by mikkeschiren** [comment]
Ok :) - If I could take over the owenership it would be great, so we can keep the history intact.

**Comment by Findus23** [comment]
Okay, it seems like you need to delete or rename `mikkeschiren/plugin-SentryLogger` so I can transfer the repository to you.

**Comment by mikkeschiren** [comment]
I have deleted that fork now.

**Comment by mikkeschiren** [comment]
Transfer done, I will move this to the digitalist-se org now, thanks! And I hope we also will get some help from the community to make this plugin even better.

**Comment by mikkeschiren** [comment]
I have now moved to the org, and will close this issue, and big thank you @Findus23 for the quick handling of this.

**Comment by Findus23** [comment]
@mikkeschiren Just one request: 

Now that you are properly maintaining the plugin instead of being a rough experiment, it would be really great if you could add a section to the description that explains the privacy implications of installing/setting up this plugin?

Because as of right now a Matomo admin without much knowledge about Sentry could result in a lot of personal information being shared (both things like the IP address of Matomo users and tracking data in exceptions). 

Also not sure how helpful it is, but you might be interested in this quick guide I wrote a while ago:

https://guides.lw1.at/how-to-install-glitchtip-without-docker/

**Comment by mikkeschiren** [comment]
That should be good to have, I will do that.

**Comment by mikkeschiren** [comment]
Added an issue, so it would not be forgotten: https://github.com/digitalist-se/MatomoPlugin-Sentry/issues/7

**Comment by mikkeschiren** [comment]
And I added short note about the guide you wrote here: https://github.com/digitalist-se/MatomoPlugin-Sentry/pull/8
